# Agent 1
comprehensive_financial_data_extraction_and_analysis:
  description: |-
    For {company_name}, efficiently extract raw financial data points for the last 3-5 fiscal years using available search and extraction tools.
    **Key Data:** Revenue / Total Sales, Net Profit, Total Assets & Liabilities, Long-Term Debt, Cash Flow from Operations, Promoter Holding, FII & DII Holdings.
    Deliver a clean, well-labeled dataset for further analysis.
  expected_output: "A markdown table or JSON object with clearly labeled, accurate raw data for each fiscal year."
  agent: comprehensive_financial_data_analyst

comprehensive_financial_health_change_analysis:
  description: |-
    Using the raw financial data for {company_name}, efficiently calculate:
      1. Year-on-Year (YoY) growth rates for Revenue and Net Profit.
      2. Key ratios: Debt-to-Equity, ROE, Net Profit Margin.
    Clearly identify and explain top 3 green flags (positives) and red flags (risks) with brief supporting data.
  expected_output: |-
    - Table of YoY growth rates and key ratios.
    - GREEN FLAGS: Top 3 positives, explained.
    - RED FLAGS: Top 3 risks, explained.
  agent: comprehensive_financial_health_change_analyst
  context:
    - comprehensive_financial_data_extraction_and_analysis

competitive_market_analysis_investment_valuation:
  description: |-
    For {company_name}, efficiently benchmark against top 3 competitors, analyze sector trends, and model valuation.
    Use web search and competitive data to assess strategic market position and investment outlook.
  expected_output: |-
    - Competitor comparison table (P/E, ROE, ROCE, debt-to-equity).
    - Sector outlook and policy impacts.
    - Strategic market position score.
    - Investment perspective summary.
  agent: investment_research_market_analyst
  context:
    - comprehensive_financial_data_extraction_and_analysis
    - comprehensive_financial_health_change_analysis

udit_review_and_assignment:
  description: |-
    **PHASE: UDIT - AUTOMATIC ORCHESTRATION & QUALITY CONTROL**
    After all specialist analyses are complete, automatically review outputs for accuracy, depth, and relevance.
    If corrections are needed, delegate tasks back to the relevant agent(s) with specific feedback.
    If all outputs meet quality standards, synthesize and approve for report writing.
    Document all feedback, revisions, and approvals.
  expected_output: |-
    - Summary of review and feedback for each analysis phase.
    - Log of any revision requests and their resolution.
    - Certification of readiness for report synthesis.
  agent: udit
  context:
    - comprehensive_financial_data_extraction_and_analysis
    - comprehensive_financial_health_change_analysis
    - competitive_market_analysis_investment_valuation

phase_5_strategic_investment_report_creation:
  description: |-
    Create a concise, executive-grade strategic investment report for {company_name} by synthesizing all specialist analysis inputs.
    Focus on key details and actionable recommendations.
    Present to Financial Analysis Orchestrator for final approval.
  expected_output: |-
    **EXECUTIVE SUMMARY:** BULLISH/BEARISH/NEUTRAL recommendation, key thesis, 3 main rationale points, target price/return (if applicable).
    **SWOT ANALYSIS:** 3 points each for strengths, weaknesses, opportunities, threats.
    **INVESTMENT DECISION RATIONALE:** Recommendation, supporting arguments, risk assessment, upside catalysts.
    **ACTIONABLE NEXT STEPS:** Investment actions, timeline, triggers, monitoring schedule.
  agent: strategic_financial_report_writer
  context:
    - udit_review_and_assignment